allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
confirmModulesPurge: false
engineStrict: false
peerDependencyRules:
  allowedVersions:
    cac: '7'
saveExact: true
strictPeerDependencies: true
verifyDepsBeforeRun: false
